spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgril
    username: root
    password: root
mybatis:
  mapper-locations: classpath:com/note/cloud_note/**/*Dao.xml
  type-aliases-package: classpath:com/note/cloud_note/**/Dao
